#!/usr/bin/env node
/**
 * sync-agents — genera la definición nativa de cada agente para cada proveedor.
 *
 * Fuente:  ~/.agents/agents/<name>.md   (frontmatter agnóstico: tier + capabilities)
 * Mapeo:   ~/.agents/agents/targets.yaml
 * Salida:  la ruta `out` de cada target
 *
 *   node scripts/sync-agents.mjs [--dry-run] [--target=<t>] [--agent=<a>] [--prune]
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync, lstatSync, unlinkSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const AGENTS_DIR = join(ROOT, 'agents');
const MARKER = 'GENERATED by sync-agents';

const args = process.argv.slice(2);
const flag = (n) => args.includes(`--${n}`);
const opt = (n) => args.find((a) => a.startsWith(`--${n}=`))?.split('=')[1];
const DRY = flag('dry-run');
const PRUNE = flag('prune');
const ONLY_TARGET = opt('target');
const ONLY_AGENT = opt('agent');

const expand = (p) => (p.startsWith('~') ? join(homedir(), p.slice(1)) : p);
const die = (msg) => {
  console.error(`\n  ERROR  ${msg}\n`);
  process.exit(1);
};

/** Separa frontmatter YAML del cuerpo. */
function parseAgent(file) {
  const raw = readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) die(`${file} no tiene frontmatter YAML válido.`);
  return { meta: yaml.load(m[1]) ?? {}, body: m[2].replace(/^\n+/, '') };
}

/**
 * Resuelve capabilities al vocabulario del target.
 * Una capability puede traer guard: "shell:readonly" → base "shell" + guard.
 */
function resolveCapabilities(caps, target, agentName) {
  const tools = [];
  const guards = [];
  for (const cap of caps ?? []) {
    const [base, guard] = String(cap).split(':');
    const mapped = target.capabilities?.[base];
    if (mapped === undefined) {
      die(`agente "${agentName}": la capability "${base}" no está mapeada en el target "${target._name}".`);
    }
    tools.push(mapped);
    if (guard) {
      const g = target.guards?.[`${base}:${guard}`];
      if (g === undefined) {
        die(`agente "${agentName}": el guard "${base}:${guard}" no está implementado en el target "${target._name}".`);
      }
      guards.push(g);
    }
  }
  return { tools, guards };
}

function resolveModel(tier, target, agentName) {
  const model = target.tiers?.[tier];
  if (!model) die(`agente "${agentName}": el tier "${tier}" no está definido en el target "${target._name}".`);
  return model;
}

/** Fusión profunda — usada por los guards y por el escape hatch `native`. */
function merge(base, extra) {
  for (const [k, v] of Object.entries(extra ?? {})) {
    if (v && typeof v === 'object' && !Array.isArray(v) && base[k] && typeof base[k] === 'object' && !Array.isArray(base[k])) {
      merge(base[k], v);
    } else {
      base[k] = v;
    }
  }
  return base;
}

// ── Emisores por formato ────────────────────────────────────────────────────

const emitters = {
  'claude-code'(meta, target, name) {
    const { tools, guards } = resolveCapabilities(meta.capabilities, target, name);
    const fm = {
      name,
      description: meta.description,
      tools: tools.flat().join(', '),
      model: resolveModel(meta.tier, target, name),
    };
    for (const g of guards) merge(fm, g);
    return fm;
  },

  opencode(meta, target, name) {
    const { tools, guards } = resolveCapabilities(meta.capabilities, target, name);
    const granted = Object.assign({}, ...tools);
    if (target.deny_unlisted) {
      for (const t of target.known_tools ?? []) if (!(t in granted)) granted[t] = false;
    }
    const fm = {
      description: meta.description,
      mode: meta.mode ?? target.defaults?.mode ?? 'subagent',
      model: resolveModel(meta.tier, target, name),
      tools: granted,
    };
    for (const g of guards) merge(fm, g);
    return fm;
  },
};

// ── Main ────────────────────────────────────────────────────────────────────

if (!existsSync(join(AGENTS_DIR, 'targets.yaml'))) die(`no encontré ${join(AGENTS_DIR, 'targets.yaml')}`);
const config = yaml.load(readFileSync(join(AGENTS_DIR, 'targets.yaml'), 'utf8'));

const agentFiles = readdirSync(AGENTS_DIR)
  .filter((f) => f.endsWith('.md'))
  .filter((f) => !ONLY_AGENT || f === `${ONLY_AGENT}.md`);

if (agentFiles.length === 0) die('no hay agentes que sincronizar.');

const stats = { created: 0, updated: 0, unchanged: 0, pruned: 0 };
const written = new Map(); // target → Set<path>

for (const [targetName, targetRaw] of Object.entries(config.targets ?? {})) {
  if (targetRaw.enabled === false) continue;
  if (ONLY_TARGET && targetName !== ONLY_TARGET) continue;

  const target = { ...targetRaw, _name: targetName };
  const emit = emitters[target.format];
  if (!emit) die(`el target "${targetName}" declara un format desconocido: "${target.format}".`);

  written.set(targetName, new Set());
  console.log(`\n▸ ${targetName}  (${target.format})`);

  for (const file of agentFiles) {
    const name = file.replace(/\.md$/, '');
    const { meta, body } = parseAgent(join(AGENTS_DIR, file));

    let fm = emit(meta, target, name);
    if (meta.native?.[targetName]) fm = merge(fm, meta.native[targetName]);

    const out = expand(target.out.replace('{name}', name));
    const content =
      `---\n${yaml.dump(fm, { lineWidth: 100, quotingType: '"' })}---\n\n` +
      `<!-- ${MARKER} desde ~/.agents/agents/${file} — no editar a mano -->\n\n` +
      body;

    written.get(targetName).add(out);

    const prev = existsSync(out) ? readFileSync(out, 'utf8').replace(/\r\n/g, '\n') : null;
    if (prev === content) {
      stats.unchanged++;
      console.log(`  =  ${name}`);
      continue;
    }

    // Nunca escribir sobre un symlink: apuntaría a la fuente y la destruiría.
    if (existsSync(out) && lstatSync(out).isSymbolicLink()) {
      die(`${out} es un symlink. Borralo antes de sincronizar (el generador escribiría sobre la fuente).`);
    }
    // Nunca pisar un archivo que no generamos nosotros.
    if (prev !== null && !prev.includes(MARKER)) {
      die(`${out} existe y no fue generado por sync-agents. Movelo o borralo antes de continuar.`);
    }

    console.log(`  ${prev === null ? '+' : '~'}  ${name}  →  ${out}`);
    if (!DRY) {
      mkdirSync(dirname(out), { recursive: true });
      writeFileSync(out, content, 'utf8');
    }
    prev === null ? stats.created++ : stats.updated++;
  }

  if (PRUNE) {
    const dir = dirname(expand(target.out.replace('{name}', 'x')));
    if (existsSync(dir)) {
      for (const f of readdirSync(dir).filter((f) => f.endsWith('.md'))) {
        const p = join(dir, f);
        if (written.get(targetName).has(p)) continue;
        if (lstatSync(p).isSymbolicLink()) continue;
        if (!readFileSync(p, 'utf8').includes(MARKER)) continue; // solo lo nuestro
        console.log(`  -  ${f}  (huérfano)`);
        if (!DRY) unlinkSync(p);
        stats.pruned++;
      }
    }
  }
}

const s = `${stats.created} creados · ${stats.updated} actualizados · ${stats.unchanged} sin cambios` +
  (PRUNE ? ` · ${stats.pruned} eliminados` : '');
console.log(`\n${DRY ? '[dry-run] ' : ''}${s}\n`);
