#!/usr/bin/env node
/**
 * sync-agents — generates each agent's native definition for each provider.
 *
 * Source:  ~/.agents/agents/<name>.md   (agnostic frontmatter: tier + capabilities)
 * Mapping: ~/.agents/agents/targets.yaml
 * Output:  each target's `out` path
 *
 *   node scripts/sync-agents.mjs [--dry-run] [--target=<t>] [--agent=<a>] [--prune]
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync, lstatSync, unlinkSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const AGENTS_DIR = join(ROOT, 'agents');
const MARKER = 'GENERATED by sync-agents';

const args = process.argv.slice(2);
const flag = (n) => args.includes(`--${n}`);
const opt = (n) => args.find((a) => a.startsWith(`--${n}=`))?.split('=')[1];
const DRY = flag('dry-run');
const PRUNE = flag('prune');
const ONLY_TARGET = opt('target');
const ONLY_AGENT = opt('agent');

const expand = (p) => (p.startsWith('~') ? join(homedir(), p.slice(1)) : p);
const die = (msg) => {
  console.error(`\n  ERROR  ${msg}\n`);
  process.exit(1);
};

/**
 * Splits the YAML frontmatter from the body.
 *
 * HTML comments in the body are stripped: they are notes for whoever maintains the
 * agent (how it's generated, where the model comes from) and don't change its
 * behavior — leaving them in would mean paying context on every invocation for
 * documentation the agent never uses.
 */
function parseAgent(file) {
  const raw = readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) die(`${file} has no valid YAML frontmatter.`);
  const body = m[2]
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/^\n+/, '');
  return { meta: yaml.load(m[1]) ?? {}, body };
}

/**
 * Resolves the placeholders a guard may carry, recursively, over any shape.
 *
 * `{AGENTS_ROOT}` is the absolute path of this repo on the machine running the
 * sync. Guards reference scripts that are versioned here (see
 * `scripts/hooks/`), and the emitted file must name them absolutely — the hook
 * runner expands neither `~` nor a relative path. Resolving it at emit time is
 * what keeps `targets.yaml` free of any one machine's paths.
 *
 * Forward slashes throughout: the emitted command is a shell string, and a
 * Windows backslash inside one is an escape, not a separator.
 */
function substitutePlaceholders(value) {
  if (typeof value === 'string') {
    return value.replaceAll('{AGENTS_ROOT}', ROOT.split('\\').join('/'));
  }
  if (Array.isArray(value)) return value.map(substitutePlaceholders);
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([k, v]) => [k, substitutePlaceholders(v)]),
    );
  }
  return value;
}

/**
 * Resolves capabilities into the target's vocabulary.
 * A capability may carry a guard: "shell:readonly" → base "shell" + guard.
 */
function resolveCapabilities(caps, target, agentName) {
  const tools = [];
  const guards = [];
  for (const cap of caps ?? []) {
    const [base, guard] = String(cap).split(':');
    const mapped = target.capabilities?.[base];
    if (mapped === undefined) {
      die(`agent "${agentName}": capability "${base}" is not mapped in target "${target._name}".`);
    }
    tools.push(mapped);
    if (guard) {
      const g = target.guards?.[`${base}:${guard}`];
      if (g === undefined) {
        die(`agent "${agentName}": guard "${base}:${guard}" is not implemented in target "${target._name}".`);
      }
      guards.push(substitutePlaceholders(g));
    }
  }
  return { tools, guards };
}

function resolveModel(tier, target, agentName) {
  const model = target.tiers?.[tier];
  if (!model) die(`agent "${agentName}": tier "${tier}" is not defined in target "${target._name}".`);
  return model;
}

/** Deep merge — used by the guards and by the `native` escape hatch. */
function merge(base, extra) {
  for (const [k, v] of Object.entries(extra ?? {})) {
    if (v && typeof v === 'object' && !Array.isArray(v) && base[k] && typeof base[k] === 'object' && !Array.isArray(base[k])) {
      merge(base[k], v);
    } else {
      base[k] = v;
    }
  }
  return base;
}

// ── Per-format emitters ────────────────────────────────────────────────────

const emitters = {
  'claude-code'(meta, target, name) {
    const { tools, guards } = resolveCapabilities(meta.capabilities, target, name);
    const fm = {
      name,
      description: meta.description,
      tools: tools.flat().join(', '),
      model: resolveModel(meta.tier, target, name),
    };
    for (const g of guards) merge(fm, g);
    return fm;
  },

  opencode(meta, target, name) {
    const { tools, guards } = resolveCapabilities(meta.capabilities, target, name);
    const granted = Object.assign({}, ...tools);
    const permission = {};
    for (const t of Object.keys(granted)) if (t !== 'patch') permission[t] = 'allow';
    if (target.deny_unlisted) {
      for (const t of target.known_tools ?? []) {
        if (t === 'patch' || t in permission) continue;
        permission[t] = 'deny';
      }
    }
    const fm = {
      description: meta.description,
      mode: meta.mode ?? target.defaults?.mode ?? 'subagent',
      model: resolveModel(meta.tier, target, name),
      permission,
    };
    for (const g of guards) merge(fm, g);
    return fm;
  },
};

// ── Main ────────────────────────────────────────────────────────────────────

if (!existsSync(join(AGENTS_DIR, 'targets.yaml'))) die(`could not find ${join(AGENTS_DIR, 'targets.yaml')}`);
const config = yaml.load(readFileSync(join(AGENTS_DIR, 'targets.yaml'), 'utf8'));

const agentFiles = readdirSync(AGENTS_DIR)
  .filter((f) => f.endsWith('.md'))
  .filter((f) => !ONLY_AGENT || f === `${ONLY_AGENT}.md`);

if (agentFiles.length === 0) die('no agents to sync.');

const stats = { created: 0, updated: 0, unchanged: 0, pruned: 0 };
const written = new Map(); // target → Set<path>

for (const [targetName, targetRaw] of Object.entries(config.targets ?? {})) {
  if (targetRaw.enabled === false) continue;
  if (ONLY_TARGET && targetName !== ONLY_TARGET) continue;

  const target = { ...targetRaw, _name: targetName };
  const emit = emitters[target.format];
  if (!emit) die(`target "${targetName}" declares an unknown format: "${target.format}".`);

  written.set(targetName, new Set());
  console.log(`\n▸ ${targetName}  (${target.format})`);

  for (const file of agentFiles) {
    const name = file.replace(/\.md$/, '');
    const { meta, body } = parseAgent(join(AGENTS_DIR, file));

    let fm = emit(meta, target, name);
    if (meta.native?.[targetName]) fm = merge(fm, meta.native[targetName]);

    const out = expand(target.out.replace('{name}', name));
    const content =
      `---\n${yaml.dump(fm, { lineWidth: 100, quotingType: '"' })}---\n\n` +
      `<!-- ${MARKER} from ~/.agents/agents/${file} — do not edit by hand -->\n\n` +
      body;

    written.get(targetName).add(out);

    const prev = existsSync(out) ? readFileSync(out, 'utf8').replace(/\r\n/g, '\n') : null;
    if (prev === content) {
      stats.unchanged++;
      console.log(`  =  ${name}`);
      continue;
    }

    // Never write over a symlink: it would point at the source and destroy it.
    if (existsSync(out) && lstatSync(out).isSymbolicLink()) {
      die(`${out} is a symlink. Delete it before syncing (the generator would write over the source).`);
    }
    // Never overwrite a file we didn't generate ourselves.
    if (prev !== null && !prev.includes(MARKER)) {
      die(`${out} exists and was not generated by sync-agents. Move or delete it before continuing.`);
    }

    console.log(`  ${prev === null ? '+' : '~'}  ${name}  →  ${out}`);
    if (!DRY) {
      mkdirSync(dirname(out), { recursive: true });
      writeFileSync(out, content, 'utf8');
    }
    prev === null ? stats.created++ : stats.updated++;
  }

  if (PRUNE) {
    const dir = dirname(expand(target.out.replace('{name}', 'x')));
    if (existsSync(dir)) {
      for (const f of readdirSync(dir).filter((f) => f.endsWith('.md'))) {
        const p = join(dir, f);
        if (written.get(targetName).has(p)) continue;
        if (lstatSync(p).isSymbolicLink()) continue;
        if (!readFileSync(p, 'utf8').includes(MARKER)) continue; // only our own
        console.log(`  -  ${f}  (orphan)`);
        if (!DRY) unlinkSync(p);
        stats.pruned++;
      }
    }
  }
}

const s = `${stats.created} created · ${stats.updated} updated · ${stats.unchanged} unchanged` +
  (PRUNE ? ` · ${stats.pruned} pruned` : '');
console.log(`\n${DRY ? '[dry-run] ' : ''}${s}\n`);
